USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[GTP_LIST]    Script Date: 11/28/2014 09:51:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GTP_LIST](
	[ID] [int] NOT NULL,
	[ID_TEC] [int] NOT NULL,
	[ID_MC] [varchar](16) NULL,
	[INDX_COL_RDG_EXCEL] [int] NULL,
	[NAME_SHR] [varchar](45) NULL,
	[NAME_FUTURE] [varchar](45) NULL,
	[PREFIX_ADMIN] [varchar](45) NULL,
	[PREFIX_PBR] [varchar](45) NULL,
	[ID_MT] [varchar](16) NULL,
	[KoeffAlarmPcur] [smallint] NULL,
 CONSTRAINT [PK_GTP_LIST] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[GTP_LIST] ADD  DEFAULT ('') FOR [ID_MT]
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[ID_TG_ASKUE_BiTEC]    Script Date: 11/28/2014 09:52:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ID_TG_ASKUE_BiTEC](
	[ID_TEC] [int] NOT NULL,
	[SENSORS_NAME] [varchar](50) NOT NULL,
	[LAST_UPDATE] [datetime] NOT NULL,
	[ID_TG] [int] NULL,
	[ID_3] [int] NULL,
	[ID_30] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[ID_TG_ASKUE_COMMON]    Script Date: 11/28/2014 09:52:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ID_TG_ASKUE_COMMON](
	[ID_TEC] [int] NOT NULL,
	[SENSORS_NAME] [varchar](50) NOT NULL,
	[LAST_UPDATE] [datetime] NOT NULL,
	[ID_TG] [int] NULL,
	[ID_3] [int] NULL,
	[ID_30] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[ID_TG_SOTIASSO]    Script Date: 11/28/2014 09:52:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ID_TG_SOTIASSO](
	[ID_TG] [int] NOT NULL,
	[ID_REALS_RV] [int] NOT NULL,
	[ID_TEC] [int] NULL,
 CONSTRAINT [PK_ID_TG_REALS_RV] PRIMARY KEY CLUSTERED 
(
	[ID_TG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[ID_TSN_ASKUE]    Script Date: 11/28/2014 09:52:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ID_TSN_ASKUE](
	[ID_USPD] [int] NOT NULL,
	[ID_CHANNEL] [int] NOT NULL,
	[ID_TEC] [int] NOT NULL,
	[ID_TG] [int] NULL,
	[Description] [varchar](100) NULL,
 CONSTRAINT [PK_ID_TSN_ASKUE] PRIMARY KEY CLUSTERED 
(
	[ID_USPD] ASC,
	[ID_CHANNEL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[ID_TSN_SOTIASSO]    Script Date: 11/28/2014 09:52:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ID_TSN_SOTIASSO](
	[ID_REALS_RV] [int] NOT NULL,
	[ID_TEC] [int] NOT NULL,
	[ID_TG] [int] NULL,
	[Description] [varchar](100) NULL,
	[DESC_REALS_RV] [varchar](66) NULL,
 CONSTRAINT [PK_ID_TSN_SOTIASSO] PRIMARY KEY CLUSTERED 
(
	[ID_REALS_RV] ASC,
	[ID_TEC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[passwords]    Script Date: 11/28/2014 09:53:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[passwords](
	[ID_EXT] [int] NOT NULL,
	[ID_ROLE] [int] NOT NULL,
	[HASH] [varchar](128) NULL,
 CONSTRAINT [PK_passwords] PRIMARY KEY CLUSTERED 
(
	[ID_EXT] ASC,
	[ID_ROLE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[passwords] ADD  DEFAULT (NULL) FOR [HASH]
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[PC_LIST]    Script Date: 11/28/2014 09:53:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PC_LIST](
	[ID_TEC] [int] NOT NULL,
	[ID] [int] NOT NULL,
	[NAME_SHR] [varchar](64) NOT NULL,
	[NAME_FUTURE] [varchar](16) NOT NULL,
 CONSTRAINT [PK_PC_LIST] PRIMARY KEY CLUSTERED 
(
	[ID_TEC] ASC,
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[roles]    Script Date: 11/28/2014 09:53:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[roles](
	[ID] [int] NULL,
	[DESCRIPTION] [varchar](16) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[roles] ADD  DEFAULT (NULL) FOR [DESCRIPTION]
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[setup]    Script Date: 11/28/2014 09:53:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[setup](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VALUE] [varchar](29) NULL,
	[KEY] [varchar](29) NOT NULL,
	[LAST_UPADTE] [datetime] NOT NULL,
	[ID_UNIT] [smallint] NULL,
 CONSTRAINT [IX_setup] UNIQUE NONCLUSTERED 
(
	[ID] ASC,
	[KEY] ASC,
	[LAST_UPADTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[SOURCE]    Script Date: 11/28/2014 09:53:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SOURCE](
	[ID] [int] NOT NULL,
	[IP] [varchar](15) NOT NULL,
	[PORT] [int] NOT NULL,
	[DB_NAME] [varchar](29) NOT NULL,
	[UID] [varchar](16) NOT NULL,
	[IGNORE] [tinyint] NOT NULL,
	[NAME_SHR] [varchar](29) NULL,
 CONSTRAINT [PK_SOURCE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SOURCE] ADD  DEFAULT ('0') FOR [ID]
GO

ALTER TABLE [dbo].[SOURCE] ADD  DEFAULT (NULL) FOR [NAME_SHR]
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[TEC_LIST]    Script Date: 11/28/2014 09:53:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TEC_LIST](
	[ID] [int] NOT NULL,
	[InUse] [tinyint] NOT NULL,
	[NAME_SHR] [varchar](45) NULL,
	[ID_SOURCE_DATA_TM] [int] NOT NULL,
	[ID_SOURCE_DATA] [int] NOT NULL,
	[ID_SOURCE_ADMIN] [int] NOT NULL,
	[ID_SOURCE_PBR] [int] NOT NULL,
	[TABLE_NAME_ADMIN] [varchar](29) NULL,
	[TABLE_NAME_PBR] [varchar](19) NOT NULL,
	[PREFIX_ADMIN] [varchar](16) NOT NULL,
	[PREFIX_PBR] [varchar](16) NOT NULL,
	[ADMIN_DATETIME] [varchar](16) NOT NULL,
	[PBR_DATETIME] [varchar](16) NOT NULL,
	[ADMIN_DIVIAT] [varchar](16) NOT NULL,
	[ADMIN_IS_PER] [varchar](16) NOT NULL,
	[ADMIN_REC] [varchar](16) NOT NULL,
	[PPBRvsPBR] [varchar](16) NOT NULL,
	[PBR_NUMBER] [varchar](16) NOT NULL,
	[TIMEZONE_OFFSET_MOSCOW] [int] NOT NULL,
	[PATH_RDG_EXCEL] [varchar](127) NULL,
	[TEMPLATE_NAME_SGN_DATA_TM] [varchar](29) NOT NULL,
	[TEMPLATE_NAME_SGN_DATA_FACT] [varchar](29) NOT NULL,
	[ID_SOURCE_MTERM] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[TG_LIST]    Script Date: 11/28/2014 09:53:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TG_LIST](
	[ID] [int] NOT NULL,
	[ID_TEC] [int] NOT NULL,
	[ID_GTP] [int] NOT NULL,
	[ID_PC] [int] NOT NULL,
	[NAME_SHR] [varchar](16) NOT NULL,
	[PREFIX] [varchar](8) NOT NULL,
	[INDX_COL_RDG_EXCEL] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TG_LIST] ADD  DEFAULT (NULL) FOR [INDX_COL_RDG_EXCEL]
GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[units]    Script Date: 11/28/2014 09:53:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[units](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[NAME_SI] [nchar](10) NULL,
	[DESCRIPTION] [nchar](10) NULL,
 CONSTRAINT [IX_units] UNIQUE NONCLUSTERED 
(
	[NAME_SI] ASC,
	[DESCRIPTION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [techsite_cfg-2.X.X]
GO

/****** Object:  Table [dbo].[users]    Script Date: 11/28/2014 09:54:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[users](
	[ID] [int] NOT NULL,
	[ID_TEC] [int] NOT NULL,
	[ID_ROLE] [int] NOT NULL,
	[IP] [varchar](15) NULL,
	[DOMAIN_NAME] [varchar](64) NULL,
	[COMPUTER_NAME] [varchar](64) NULL,
	[DESCRIPTION] [varchar](45) NOT NULL,
	[InUse] [smallint] NOT NULL,
	[LAST_CHANGED_AT] [datetime] NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[users] ADD  DEFAULT (NULL) FOR [IP]
GO

ALTER TABLE [dbo].[users] ADD  DEFAULT (NULL) FOR [DOMAIN_NAME]
GO

ALTER TABLE [dbo].[users] ADD  DEFAULT (NULL) FOR [COMPUTER_NAME]
GO

ALTER TABLE [dbo].[users] ADD  CONSTRAINT [DF_users_InUse]  DEFAULT ((0)) FOR [InUse]
GO

